main: BanManager\BanManager

name: BanManager
author: Taylcd
website: https://github.com/Taylcd/BanManager

version: 1.0.0_pre1
api:
  - 3.0.0-ALPHA7
  - 3.0.0-ALPHA8
  - 3.0.0-ALPHA9
  - 3.0.0-ALPHA10