# Don't touch it!
config-version: 1

# Supported languages
# - English(eng)
# - Simplified Chinese(chs)
lang: eng

# Command names
commands:
  ban: ban
  ban-ip: ban-ip
  unban: pardon
  unban-ip: pardon-ip
  banlist: banlist
  mute: mute
  unmute: unmute
  mutelist: mutelist
  block: block
  block-ip: block-ip

# Enable if you're overriding default command names
override-default-commands: true

# Supported providers: YAML, MySQL
database-provider: YAML

# mysql-settings:
#   host: 127.0.0.1
#   username: root
#   password: root
#   database: BanManager
#   port: 3306