# Don't touch it!
config-version: 1

# Supported languages
# - English(eng)
# - Simplified Chinese(chs)
lang: eng

# Command names
commands:
  ban: ban
  ban-ip: ban-ip
  unban: pardon
  unban-ip: pardon-ip
  banlist: banlist
  mute: mute
  unmute: unmute
  mutelist: mutelist

# Enable if you're overriding default command names
override-default-commands: true